### ISSUE TITLE
你好，请问下thunder这个model引用的是什么开源库吗

### ISSUE THREAD

**Issue by 123lxw123** [oceanzhang01/MiniThunder#1]

**Comment by oceanzhang01** [comment]
破解的手机迅雷.

**Comment by 123lxw123** [comment]
` /**
     * 获取某个文件的本地proxy url,如果是音视频文件可以实现变下边播
     * @param filePath
     * @return
     */
public synchronized String getLoclUrl(String filePath) {
        XLTaskLocalUrl localUrl = new XLTaskLocalUrl();
        XLDownloadManager.getInstance().getLocalUrl(filePath,localUrl);
        return localUrl.mStrUrl;
    }`
通过这个方法获取的 url 用普通的播放器就可以边下边播吗

**Comment by 123lxw123** [comment]
另外对破解的方法也很感兴趣，方便提供下学习资料的链接或者技术关键字？

**Comment by 123lxw123** [comment]
你好，请问下 app 重新打开后如何获取之前的下载任务信息？
