### ISSUE TITLE
请问如何实现边下边播

### ISSUE THREAD

**Issue by marscl** [oceanzhang01/MiniThunder#2]

**Comment by oceanzhang01** [comment]
/**
     * 获取某个文件的本地proxy url,如果是音视频文件可以实现变下边播
     * @param filePath
     * @return
     */
    public synchronized String getLoclUrl(String filePath) {
        XLTaskLocalUrl localUrl = new XLTaskLocalUrl();
        XLDownloadManager.getInstance().getLocalUrl(filePath,localUrl);
        return localUrl.mStrUrl;
    }

**Comment by marscl** [comment]
close

**Comment by marscl** [comment]
请问用什么播放器可以播放

**Comment by handsome51jia** [comment]
这个我试了，无法播放，我获得的链接是这样的http://127.0.0.1:35043/%252Fstorage%252Femulated%252F0%252Fde151b52e393656e83359d19079c94381701be3f.torrent

**Comment by xingyuan1998** [comment]
你们可以播放种子文件吗，
